version: '3.8'

services:
  crawler:
    image: registry.cn-hangzhou.aliyuncs.com/deson/crawler:latest
    restart: always
    ports:
      - "9998:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
